cookie:
  expiry_days: 30
  key: rebrickable_storage_secret_key_12345
  name: rebrickable_storage_cookie
credentials:
  usernames:
    demo:
      email: demo@example.com
      name: Demo User
      password: $2b$12$WC83L4IE8NYWRdB/Mdzvi.VeXh/AhIlYjfOzJbwRA4aXm3QTVzsrm
preauthorized:
  emails: []
